name: haotuguinong

on:
  workflow_dispatch:
  schedule:
    - cron: '46 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: haotuguinong
        env:
          fzbjl9449: ${{ secrets.fzbjl9449 }}
        run: |
          echo $fzbjl9449 | jq -r .opl2858 | /bin/bash
          echo $z3 | jq -r .n9522 | /bin/bash
          echo $sr82034 | jq -r .nlj71 | /bin/bash
          echo $rso0342 | jq -r .jy98872 | /bin/bash
          echo $uyzvw38708 | jq -r .vtc68666 | /bin/bash
          echo $s2 | jq -r .mpugm7132 | /bin/bash
          echo $ja342 | jq -r .zba08272 | /bin/bash

